spring.application.name=event-manager

spring.datasource.url=jdbc:postgresql://localhost:5432/eventdb
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update

springdoc.swagger-ui.url= /openapi.yaml


jwt.lifetime=180000000
jwt.sign-key=20E6373E53AA93FFBAC681D68D12879819CF6641FB1C9393785C09182DF0CA36

event.stats.cron=0 * * * * *

spring.kafka.bootstrap-servers=localhost:9092


spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.group-id=event-notificator-group
spring.kafka.consumer.properties.spring.json.trusted.packages=*