spring.application.name=event-notificator


spring.datasource.url=jdbc:postgresql://postgres-event-notificator:5432/notificatordb
spring.datasource.username=notif_user
spring.datasource.password=notif_password
spring.jpa.hibernate.ddl-auto=update


app.kafka.topic=event-changes

spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=event-notificator-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted-packages=*


app.notifications.cleanup.cron=0 */10 * * * *
app.notifications.cleanup.days=7
